services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=oss_db
      - DB_USER=root
      - DB_PASSWORD=example